# Generated by Django 3.1.14 on 2022-11-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('place_img_src', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('theme_img_src', models.TextField(blank=True, null=True)),
                ('theme_like_cnt', models.IntegerField(blank=True, null=True)),
                ('is_shared', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=10, null=True)),
                ('account_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedPlace',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.user')),
            ],
            options={
                'db_table': 'liked_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedTheme',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.user')),
            ],
            options={
                'db_table': 'liked_theme',
                'managed': False,
            },
        ),
    ]
